name: wtoolset
description: 韦斌工具集

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image: ^4.1.3
  video_player: ^2.2.19
  provider: ^6.0.2
  mobile_scanner: ^6.0.2

  flutter_ume_plus: ^4.1.0
  flutter_ume_kit_ui_plus: ^4.1.0
  flutter_ume_kit_device_plus: ^4.1.0
  flutter_ume_kit_perf_plus: ^4.1.0
  flutter_ume_kit_show_code_plus: ^4.0.0
  flutter_ume_kit_console_plus: ^4.0.0
  flutter_ume_kit_dio_plus: ^4.1.1

  record: ^5.2.0
  path: ^1.9.0
  path_provider: ^2.1.5
  wakelock_plus: ^1.2.8

  universal_io: ^2.2.2

  image_picker: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/efe-kurnaz.jpg
    - assets/rodion-kutsaev.jpeg
    - assets/steve-johnson.jpeg


