name: wtoolset
description: 韦斌工具集

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image: ^4.1.3
  video_player: ^2.2.19
  provider: ^6.0.2
  mobile_scanner: ^3.5.2
  flutter_ume_plus: ^3.0.0
  flutter_ume_kit_ui_plus: ^2.0.0
  flutter_ume_kit_device_plus: ^2.0.0
  flutter_ume_kit_perf_plus: ^2.0.0
  flutter_ume_kit_show_code_plus: ^3.0.0
  flutter_ume_kit_console_plus: ^2.0.0
  flutter_ume_kit_dio_plus: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/efe-kurnaz.jpg
    - assets/rodion-kutsaev.jpeg
    - assets/steve-johnson.jpeg


